<img src="../img/itq.jpg" style="width:90px;"> <br>
<h2 style="font-family: 'Times New Roman', Times, serif; text-align: center;">PAO25_26_25_Python_Normalizacion_Estandarizacion</h2>
<h2 style="font-family: 'Times New Roman', Times, serif; text-align: center;">Marzo 25, 2026</h2>
<p style="font-family: 'Times New Roman', Times, serif; font-weight:bold; font-size:16px;">
0.1 Primer Modulo - Python, Normalizacion, Estandarizacion
</p>

<img src="../img/img2.png" alt="imagen" style="display:block; margin: 0 auto;"> </br>

*Bryan Justin Antamba*
<div style="font-family: 'Times New Roman', Times, serif;">
    
## **Normalizacion**

Ejemplo practico:

Ejercicio de Normalización

Una estación meteorológica recopila datos de 4 muestras ambientales con 4 atributos cada una: Peso (kg), Altura (cm), Edad (años) y Salario (USD). Dado que cada atributo maneja escalas completamente diferentes, se requiere aplicar una normalización min-max para transformar todos los valores al rango continuo [0, 1], de forma que los atributos sean comparables entre sí. Aplica la fórmula correspondiente por columna de forma independiente y verifica que el mínimo de cada columna sea 0 y el máximo sea 1.
Los datos registrados son los siguientes:

Muestra 1: Peso = 10 kg, Altura = 200 cm, Edad = 30 años, Salario = 5000 USD
Muestra 2: Peso = 40 kg, Altura = 150 cm, Edad = 25 años, Salario = 8000 USD
Muestra 3: Peso = 20 kg, Altura = 300 cm, Edad = 45 años, Salario = 3000 USD
Muestra 4: Peso = 50 kg, Altura = 100 cm, Edad = 20 años, Salario = 12000 USD

</div>

In [1]:
# numpy nos da operaciones vectorizadas (min, max) por columna
# pandas nos permite visualizar la matriz como tabla legible
import numpy as np
import pandas as pd

In [18]:
# Definimos la matriz de datos (4 filas = muestras, 4 columnas = atributos)
datos = np.array([
    [10, 200, 30,  5000],
    [40, 150, 25,  8000],
    [20, 300, 45,  3000],
    [50, 100, 20, 12000],
], dtype=float)

columnas = ['Peso', 'Altura', 'Edad', 'Salario']
df_original = pd.DataFrame(datos, columns=columnas)
#Visualizacion de matriz original
df_original

   Peso  Altura  Edad  Salario
0  10.0   200.0  30.0   5000.0
1  40.0   150.0  25.0   8000.0
2  20.0   300.0  45.0   3000.0
3  50.0   100.0  20.0  12000.0

In [3]:
# axis=0 → operación a lo largo de las filas → resultado por columna
col_min = datos.min(axis=0)
col_max = datos.max(axis=0)

print("Mínimo por columna:", col_min)
print("Máximo por columna:", col_max)
print("Rango  por columna:", col_max - col_min)

Mínimo por columna: [  10.  100.   20. 3000.]
Máximo por columna: [   50.   300.    45. 12000.]
Rango  por columna: [  40.  200.   25. 9000.]

In [4]:
# Fórmula: x_norm = (x - min(columna)) / (max(columna) - min(columna))
rango = col_max - col_min
datos_norm = (datos - col_min) / rango

df_norm = pd.DataFrame(datos_norm, columns=columnas)
print("Matriz normalizada [0, 1]:")
df_norm.round(4)

Matriz normalizada [0, 1]:

   Peso  Altura  Edad  Salario
0  0.00    0.50   0.4   0.2222
1  0.75    0.25   0.2   0.5556
2  0.25    1.00   1.0   0.0000
3  1.00    0.00   0.0   1.0000

In [5]:
# Tras la normalización el mínimo debe ser 0 y el máximo 1
print("Mín por columna (debe ser 0):", datos_norm.min(axis=0))
print("Máx por columna (debe ser 1):", datos_norm.max(axis=0))

Mín por columna (debe ser 0): [0. 0. 0. 0.]
Máx por columna (debe ser 1): [1. 1. 1. 1.]

In [6]:
df_comp = pd.concat(
    [df_original, df_norm.round(4)],
    keys=['Original', 'Normalizada'],
    axis=1
)
df_comp

  Original                       Normalizada
      Peso Altura  Edad  Salario        Peso Altura Edad Salario
0     10.0  200.0  30.0   5000.0        0.00   0.50  0.4  0.2222
1     40.0  150.0  25.0   8000.0        0.75   0.25  0.2  0.5556
2     20.0  300.0  45.0   3000.0        0.25   1.00  1.0  0.0000
3     50.0  100.0  20.0  12000.0        1.00   0.00  0.0  1.0000

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
datos_sklearn = scaler.fit_transform(datos)

print("Resultado con sklearn (debe ser idéntico):")
print(np.round(datos_sklearn, 4))
print("\n¿Igual al cálculo manual?", np.allclose(datos_sklearn, datos_norm))

Resultado con sklearn (debe ser idéntico):
[[0.2353 0.7333 0.375  0.1667]
 [1.     0.     1.     1.    ]
 [0.     1.     0.     0.    ]
 [0.6471 0.4    0.625  0.5   ]]

¿Igual al cálculo manual? False

<div style="font-family: 'Times New Roman', Times, serif;">
    
## **Estandarizacion**

Ejemplo practico:

Una estación de monitoreo ambiental registra 4 variables atmosféricas sobre 4 muestras: Temperatura (°C), Presión (hPa), Humedad (%) y CO₂ (ppm). Debido a que las magnitudes de cada variable son muy distintas, se requiere aplicar una estandarización z-score para que cada atributo tenga media = 0 y desviación típica = 1, permitiendo comparar las variables en una misma escala. Aplica la fórmula correspondiente por columna de forma independiente y verifica que la media de cada columna sea 0 y su desviación estándar sea 1.
Los datos registrados son los siguientes:

Muestra 1: Temperatura = 22 °C, Presión = 1013 hPa, Humedad = 55 %, CO₂ = 400 ppm
Muestra 2: Temperatura = 35 °C, Presión = 980 hPa, Humedad = 80 %, CO₂ = 650 ppm
Muestra 3: Temperatura = 18 °C, Presión = 1025 hPa, Humedad = 40 %, CO₂ = 350 ppm
Muestra 4: Temperatura = 29 °C, Presión = 998 hPa, Humedad = 65 %, CO₂ = 500 ppm
</div>

In [9]:
# Matriz de 4 muestras × 4 atributos con escalas muy distintas
# Columnas: Temperatura (°C), Presión (hPa), Humedad (%), CO2 (ppm)
datos = np.array([
    [ 22,  1013, 55,  400],
    [ 35,   980, 80,  650],
    [ 18,  1025, 40,  350],
    [ 29,   998, 65,  500],
], dtype=float)

columnas = ['Temp (°C)', 'Presión (hPa)', 'Humedad (%)', 'CO2 (ppm)']
df_original = pd.DataFrame(datos, columns=columnas)
print("Matriz ORIGINAL:")
df_original

Matriz ORIGINAL:

   Temp (°C)  Presión (hPa)  Humedad (%)  CO2 (ppm)
0       22.0         1013.0         55.0      400.0
1       35.0          980.0         80.0      650.0
2       18.0         1025.0         40.0      350.0
3       29.0          998.0         65.0      500.0

In [10]:
# axis=0 → calcula a lo largo de las filas → un valor por columna
# ddof=0 → desviación estándar poblacional (divide entre N)
# ddof=1 → desviación estándar muestral  (divide entre N-1)
media = datos.mean(axis=0)
desv  = datos.std(axis=0, ddof=0)

print("Media por columna:             ", media)
print("Desviación típica por columna: ", desv.round(4))

Media por columna:              [  26. 1004.   60.  475.]
Desviación típica por columna:  [  6.5192  16.8375  14.5774 114.5644]

In [11]:
# Fórmula: x_est = (x − media(columna)) / desv(columna)
# El resultado es el z-score: cuántas desviaciones típicas
# se aleja cada valor de su media.
datos_est = (datos - media) / desv

df_est = pd.DataFrame(datos_est, columns=columnas)
print("Matriz ESTANDARIZADA (z-score):")
df_est.round(4)

Matriz ESTANDARIZADA (z-score):

   Temp (°C)  Presión (hPa)  Humedad (%)  CO2 (ppm)
0    -0.6136         0.5345       -0.343    -0.6547
1     1.3805        -1.4254        1.372     1.5275
2    -1.2271         1.2472       -1.372    -1.0911
3     0.4602        -0.3563        0.343     0.2182

In [12]:
# Comprobación: tras la estandarización cada columna
# debe tener media ≈ 0 y desviación típica ≈ 1
media_est = datos_est.mean(axis=0)
desv_est  = datos_est.std(axis=0, ddof=0)

print("Media por columna  (debe ser ≈ 0):", media_est.round(10))
print("Desv.  por columna (debe ser ≈ 1):", desv_est.round(10))

Media por columna  (debe ser ≈ 0): [ 0.  0.  0. -0.]
Desv.  por columna (debe ser ≈ 1): [1. 1. 1. 1.]

In [13]:
# El z-score indica cuántas desviaciones típicas se aleja
# cada valor de la media de su columna
for col in columnas:
    z_vals = df_est[col].round(4).tolist()
    print(f"{col:20} → z-scores: {z_vals}")

Temp (°C)            → z-scores: [-0.6136, 1.3805, -1.2271, 0.4602]
Presión (hPa)        → z-scores: [0.5345, -1.4254, 1.2472, -0.3563]
Humedad (%)          → z-scores: [-0.343, 1.372, -1.372, 0.343]
CO2 (ppm)            → z-scores: [-0.6547, 1.5275, -1.0911, 0.2182]

In [14]:
# Comparación lado a lado con MultiIndex
df_comp = pd.concat(
    [df_original, df_est.round(4)],
    keys=['Original', 'Estandarizada (z)'],
    axis=1
)
df_comp

   Original                                     Estandarizada (z)  \
  Temp (°C) Presión (hPa) Humedad (%) CO2 (ppm)         Temp (°C)
0      22.0        1013.0        55.0     400.0           -0.6136
1      35.0         980.0        80.0     650.0            1.3805
2      18.0        1025.0        40.0     350.0           -1.2271
3      29.0         998.0        65.0     500.0            0.4602


  Presión (hPa) Humedad (%) CO2 (ppm)
0        0.5345      -0.343   -0.6547
1       -1.4254       1.372    1.5275
2        1.2472      -1.372   -1.0911
3       -0.3563       0.343    0.2182

In [16]:
from sklearn.preprocessing import StandardScaler

# StandardScaler aplica la misma fórmula z-score
# Ventaja: guarda los parámetros para escalar datos nuevos
scaler = StandardScaler()
datos_sklearn = scaler.fit_transform(datos)

print("Resultado con sklearn:")
print(np.round(datos_sklearn, 4))
print("\n¿Igual al cálculo manual?", np.allclose(datos_sklearn, datos_est))

Resultado con sklearn:
[[-0.6136  0.5345 -0.343  -0.6547]
 [ 1.3805 -1.4254  1.372   1.5275]
 [-1.2271  1.2472 -1.372  -1.0911]
 [ 0.4602 -0.3563  0.343   0.2182]]

¿Igual al cálculo manual? True